In [2]:
import numpy as np

In [3]:
np.array([0, 1])

array([0, 1])

In [14]:
from Tensor import Tensor

a = Tensor([1, 5, 6])
b = Tensor([2, 2, 1])
c = Tensor([4, 6, 6])

res = a**2 * b - c
res.backward()
res.item, a.grad,

(array([-2., 44., 30.], dtype=float32),
 array([ -4., -20., -12.], dtype=float32))

In [48]:
from torch import Tensor

a = Tensor([5])
a.requires_grad = True

b = Tensor([10])
b.requires_grad = True

c =  Tensor([2])
c.requires_grad = True

res = a * b * c
res.backward()
print("A grad: ", a.grad)
print("B grad: ", b.grad)
print("RES: ", res.item())

A grad:  tensor([20.])
B grad:  tensor([10.])
RES:  100.0


In [ ]:
import torch


class MyReLU(torch.autograd.Function):
    """
    We can implement our own custom autograd Functions by subclassing
    torch.autograd.Function and implementing the forward and backward passes
    which operate on Tensors.
    """

    @staticmethod
    def forward(ctx, input):
        """
        In the forward pass we receive a Tensor containing the input and return
        a Tensor containing the output. ctx is a context object that can be used
        to stash information for backward computation. You can cache arbitrary
        objects for use in the backward pass using the ctx.save_for_backward method.
        """
        ctx.save_for_backward(input)
        return input.clamp(min=0)

    @staticmethod
    def backward(ctx, grad_output):
        """
        In the backward pass we receive a Tensor containing the gradient of the loss
        with respect to the output, and we need to compute the gradient of the loss
        with respect to the input.
        """
        input, = ctx.saved_tensors
        grad_input = grad_output.clone()
        grad_input[input < 0] = 0
        return grad_input


x0 = torch.tensor([1., 1.], requires_grad=True)
relu = MyReLU.apply

y_pred = relu(x0)
y_pred.mean().backward()
y_pred, x0.grad

RuntimeError: grad can be implicitly created only for scalar outputs

In [46]:
test = np.array([1, 2])
test.shape

(2,)