In [1]:
import torch
from simplegrad import Tensor

vals = [1., 2., 4.]
x = torch.tensor(vals, requires_grad=True)
x.retain_grad()
b = x + 1
b[0:2] = 2 * 5 / 2 + b[0:2]
b.retain_grad()
b.backward(torch.ones_like(b))
b, b.grad, x.grad

/opt/anaconda3/envs/simplegrad/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


(tensor([7., 8., 5.], grad_fn=<CopySlices>),
 tensor([1., 1., 1.]),
 tensor([1., 1., 1.]))

In [2]:
x = Tensor(vals, requires_grad=True)
b = x + 1
b[0:2] = 2 * 5 / 2 + b[0:2]
b.backward()
b.item, b.grad, x.grad

C [1. 2. 4.]
Y 1
C [2. 3.]
Y 5.0


(array([7., 8., 5.], dtype=float32),
 array([1., 1., 1.], dtype=float32),
 array([0., 0., 1.], dtype=float32))

In [ ]:
x = Tensor(vals, requires_grad=True)
2 + x 

Tensor(item=[3. 4. 6.], requires_grad=True, grad_fn=<AddBackward>)